### ISSUE TITLE
Demo app?

### ISSUE THREAD

**Issue by aminemat** [equip/framework#55]
Hey @shadowhand,

I made a demo app using equip 1 https://github.com/aminemat/scheduler.
The app was for a temporary use and still lacks many things, I was planning to ditch it as soon as it serves it's purpose, but now that Equip 2 is here I could refactor it and you could link it in the docs as a non official demo app for Equip.

Having a functional demo app with proper tests can go a long way in explaining the merits of the framework but I don't want to invest time in it if you don't think it's a good idea.

Thoughts?

**Comment by shadowhand** [comment]
It looks really good! I've forked it if you want to delete your version. If we end up using it, we'll be sure to give credit!

**Comment by aminemat** [comment]
Sounds good!
