### ISSUE TITLE
Zend Diactoros package not bundled

### ISSUE THREAD

**Issue by MrHash** [equip/framework#67]
Sample bootstrap example requires explicit inclusion of `zendframework/zend-diactoros` package in order to work, so best either advise the user or include for dev.

**Comment by shadowhand** [comment]
This is intentional, we've added an explicit dependency in `equip/project`. However, we should also add it to the docs.

**Comment by MrHash** [comment]
Got it. In my haste I didn't notice the project repo. thanks.
