### ISSUE TITLE
Move core configuration code to separate library?

### ISSUE THREAD

**Issue by elazar** [equip/framework#68]
I'd like to be able to use the core configuration code (i.e. `ConfigurationInterface` and `ConfigurationSet`) apart from the rest of the framework. I think there may be sufficient value in this notion to warrant moving it to its own repository.

It's under its own sub-namespace, so no namespace changes would be needed. The only potential difficulty I can see that it introducing is that any major version upgrades to `equip/structure` dependency would have to be done on both repositories simultaneously to avoid version conflicts.

**Comment by elazar** [comment]
For an idea of [what this would look like](https://github.com/elazar/auryn-configuration/).

**Comment by shadowhand** [comment]
Makes sense to me. The only compatibility issue I see with your implementation is that Equip's configuration set is based on [`Set`](https://github.com/equip/structure/blob/master/src/Set.php) which has additional functionality that would be lost.

**Comment by elazar** [comment]
@shadowhand Is that functionality that we're really making use of particularly often? In terms of keeping the contained elements unique, if we're not already doing that ourselves, it should really be corrected anyway. In my experience, we've generally just specified a list in the bootstrap and not really used any of the other set-specific features.

**Comment by ameech** [comment]
@elazar @shadowhand where are you guys at with this one? I'm waiting on this for `equip/console`.

**Comment by shadowhand** [comment]
@elazar we can split configuration for 3.x `dev` branch, but cannot remove functionality within the 2.x `master` branch. However, there is nothing to prevent the usage of split configuration within existing 2.x projects.
