### ISSUE TITLE
Confusion...

### ISSUE THREAD

**Issue by nbish11** [equip/framework#70]
So I've recently discovered the ADR pattern and am pretty much set on it. However, when trying to decide on which framework I would like to use, I came across this one and [Spark](https://github.com/sparkphp/spark). Whats going on here? They both seem exactly the same.

**Comment by shadowhand** [comment]
If you look at the readme in spark you will see that it has been deprecated
in favor of equip.

On Fri, Jul 1, 2016, 07:25 Nathan <notifications@github.com> wrote:

> So I've recently discovered the ADR pattern and am pretty much set on it.
> However, when trying to decide on which framework I would like to use, I
> came across this one and Spark <https://github.com/sparkphp/spark>. Whats
> going on here? They both seem exactly the same.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/equip/framework/issues/70>, or mute the thread
> <https://github.com/notifications/unsubscribe/AACVOxxX8GRw7UxMj2BNxbtjlRefq4qeks5qRQdUgaJpZM4JDGO3>
> .
>
-- 

Woody Gilk
http://about.me/shadowhand

**Comment by nbish11** [comment]
[README.md](https://github.com/sparkphp/spark/blob/master/README.md) from Spark:

>A tiny and powerful PHP micro-framework created and maintained by the engineering team at When I Work.
>
>Attempts to be PSR-1, PSR-2, PSR-4 and PSR-7 compliant. Also uses the ADR pattern. You should too!
>
>To get started, check out the documentation. There's also a sample project that shows the best way to use this framework and is a quick way to start a new project.

But thanks for clearing up the confusion.

**Comment by shadowhand** [comment]
@nbish11 sorry I thought we added a message to that... apologies for misleading you.
