### ISSUE TITLE
Output as HTML

### ISSUE THREAD

**Issue by designermonkey** [equip/framework#73]
I have tried to read the docs, and tried to get a handle on how to just output html, and I just can't for the life of me figure out how.

Any helpers?

**Comment by shadowhand** [comment]
This is controlled by the Responders. We allow for [Plates](http://platesphp.com/) to be used, see http://equipframework.readthedocs.io/en/latest/#using-plates

**Comment by ameech** [comment]
@designermonkey, were you able to figure it out?

**Comment by designermonkey** [comment]
I'll be honest, I haven't had the time to look again; it's a personal project.

I'll close this though.

**Comment by crybat** [comment]
Activate PlatesConfiguration and PlatesResponderConfiguration in index.php.

PlatesConfiguration uses the PLATES_DIRECTORY env variable, so make sure to set it in your .env.

In the payload set which template to use `->withSetting('template', 'someTemplate')`.

After this, if you have to set the request headers accordingly to return as JSON.
