### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [equip/framework#92]
As title, is this project still maintain?

It seems that this project has been inactive for about whiles.

Once this project status is on maintained, let me do some contributions on that to keep this package better :).

**Comment by shadowhand** [comment]
I do not believe it is. There are other options available that have bigger communities, such as [Slim](http://www.slimframework.com).

**Comment by peter279k** [comment]
Hi @shadowhand, thanks for your reply.

You mean that this project is going to be archived and inactive?

**Comment by bvisness** [comment]
At this point we're only using Equip for one or two things internally at When I Work, and we don't have plans to use it for new projects. You'd be much better off using another PHP framework with more community support, like the one @shadowhand mentioned.

**Comment by peter279k** [comment]
Ok. Thanks for all reply. Closed due to clear explanation and suggestion.
